config/routes.rb
Rails.application.routes.draw do
    
  get 'users/index'

  get 'users/new'

  get 'users/show'

  get 'users/edit'

  get 'users/create'

  get 'users/update'

  get 'users/destroy'

  	get 'loja' => 'loja#index', as: :loja
  	post 'busca_cidades' => 'loja#busca_cidades', as: :busca_cidades
  	get 'cardapio' => 'loja#cardapio', as: :cardapio
    get 'cardapio/:state' => 'loja#cardapio_state', as: :cardapio_state
    get 'cardapio/:state/:name' => 'loja#cardapio_state_name', as: :cardapio_state_name
  	post 'login' => 'loja#login', as: :login
  	get 'pizzas/:guide' => 'loja#pizzas', as: :pizzas
  	get 'modeljson' => 'loja#modeljson', as: :modeljson
  	get 'cart' => 'loja#cart', as: :cart
    get 'checkout' => 'loja#checkout', as: :checkout
    post 'checkout_confirm' => 'loja#checkout_confirm', as: :checkout_confirm
    post 'add_combo' => 'loja#add_combo', as: :add_combo
    post 'add_combo_sweet' => 'loja#add_combo_sweet', as: :add_combo_sweet
    post 'add_combo_beverages' => 'loja#add_combo_beverages', as: :add_combo_beverages
  	post 'add_cart' => 'loja#add_cart', as: :add_cart
    post 'add_sweet' => 'loja#add_sweet', as: :add_sweet
    post 'edit_cart' => 'loja#edit_cart', as: :edit_cart
    post 'edit_sweet' => 'loja#edit_sweet', as: :edit_sweet
    get 'del/:name' => 'loja#del', as: :del
    get 'sweet_del/:name' => 'loja#sweet_del', as: :sweet_del
    post 'cep' => 'loja#cep', as: :cep
    post 'rss' => 'loja#rss', as: :rss
    get 'tamanho/:id' => 'loja#tamanho', as: :tamanho
    get 'massa/:id' => 'loja#massa', as: :massa
    get 'borda/:id' => 'loja#borda', as: :borda
    get 'integral' => 'loja#integral', as: :integral
    get 'bebidas/:price/:id/:qtd' => 'loja#bebidas', as: :bebidas
    get 'bebemenos/:id' => 'loja#bebemenos', as: :bebemenos
    get 'profile' => 'loja#profile', as: :profile
    get 'combo/:id' => 'loja#combo', as: :combo
    get 'limparcart' => 'loja#limparcart', as: :limparcart
    get 'remove_combo/:id' => 'loja#remove_combo', as: :remove_combo
    get 'remove_pizza_combo/:id' => 'loja#remove_pizza_combo', as: :remove_pizza_combo
    get 'remove_doce_combo/:id' => 'loja#remove_doce_combo', as: :remove_doce_combo
    get 'remove_bebida_combo/:id' => 'loja#remove_bebida_combo', as: :remove_bebida_combo

    get 'unidades' => 'home#unidades', as: :unidades
    get 'novo_hamburgo' => 'home#novo_hamburgo', as: :novo_hamburgo

    post 'contato' => 'home#contato', as: :contato
    post 'applycoupon' => 'loja#applycoupon', as: :applycoupon

    get 'removeaddress/:id' => 'loja#removeaddress', as: :removeaddress
    get 'removecard/:id' => 'loja#removecard', as: :removecard

    get 'selend/:id' => 'loja#selend', as: :selend

    post 'updateabout' => 'loja#updateabout', as: :updateabout
    post 'addaddress' => 'loja#addaddress', as: :addaddress
    post 'addcard' => 'loja#addcard', as: :addcard
    get 'cadastre' => 'home#cadastre', as: :cadastre

    post 'novouser' => 'home#novouser', as: :novouser

    get 'home' => 'home#index', as: :home
    get 'logout' => 'loja#logout', as: :logout

    get 'auth/facebook' => 'loja#loginfacebook', as: :auth_provider
    get 'auth/facebook/callback' => 'loja#loginfacebook'
    get 'auth/failure' => 'loja#login#failure', as: "auth_failure"

    root 'home#index'
     
end

app/controllers/loja_controller.rb
class LojaController < ApplicationController

  def index
  	@states = Store.distinct(:state)
  end

  def rss
    redirect_to root_path
  end

  def tamanho
    session[:tamanho] = params[:id]
    redirect_to cardapio_path
  end

  def massa
    session[:massa] = params[:id]
    redirect_to cardapio_path
  end

  def borda
    session[:borda] = params[:id]
    redirect_to cardapio_path
  end

  def integral
    if session[:integral] == '1'
      session[:integral] = '0'
      redirect_to cardapio_path
    else
      session[:integral] = '1'
      redirect_to cardapio_path
    end
  end
  
  def logout
    cookies[:session_id] = nil
    
    session[:address_id] = nil
    session[:store] = nil
    session[:user] = nil
    session[:logged] = nil
    session[:name] = nil
    session[:email] = nil
    session[:picture] = nil
    session[:gender] = nil
    session[:facebook] = nil
    session[:balance] = nil
    session[:phone] = nil
    session[:cpf] = nil
    session[:caixa] = nil
    session[:pizzas] = nil
    session[:bebidas] = nil
    session[:tamanho] = nil
    session[:massa] = nil
    session[:borda] = nil
    session[:integral] = nil
    session[:combo] = nil
    session[:coupon] = nil

    redirect_to home_path, notice: 'Logout efetuado com Sucesso'
  end

  def addaddress
    RestClient.post('http://pizzaprime.herokuapp.com/webservices/account/addAddress', { :name => params[:address][:name], :zip => params[:address][:cep], :street => params[:address][:street], :number => params[:address][:number], :state => params[:address][:state], :phone => params[:address][:phone], :city => params[:address][:city], :type => params[:address][:type].to_i, :complement => params[:address][:complement], :neighborhood => params[:address][:neighborhood]  }, :cookies => { '_session_id' => cookies[:session_id] } ){ |response, request, result, &block|
        
        redirect_to profile_path, notice: 'Endereço inserido com Sucesso'
        #render json: response.body

    }
  end

  def addcard
    opa = params[:card][:vencimento].split('/')
    cartao = params[:card][:number].split('-')
    nome = "Terminado em #{cartao[3]}"
    card = PagarMe::Card.new({
      :card_number => params[:card][:number].gsub('-', ''),
      :card_holder_name => params[:card][:titular],
      :card_expiration_month => opa[0],
      :card_expiration_year => opa[1],
      :card_cvv => params[:card][:cvv]
    });

    teste = card.create

    RestClient.post('http://pizzaprime.herokuapp.com/webservices/account/addCard', { :name => nome, :brand => teste.brand, :cpf => params[:card][:cpf], :id => teste.id   }, :cookies => { '_session_id' => cookies[:session_id] } ){ |response, request, result, &block|
        
        redirect_to profile_path, notice: 'Cartão inserido com Sucesso'
        #render json: response.body

    }
  end

  def removecard
    RestClient.delete('http://pizzaprime.herokuapp.com/webservices/account/removeCard', :params => { 'card' => params[:id] }, :cookies => { '_session_id' => cookies[:session_id] } ){ |response, request, result, &block|
        
        redirect_to profile_path, notice: 'Cartão removido com Sucesso'
        #render json: response.body

    }
  end

  def removeaddress
    RestClient.delete('http://pizzaprime.herokuapp.com/webservices/account/removeAddress', :params => { 'address' => params[:id] }, :cookies => { '_session_id' => cookies[:session_id] } ){ |response, request, result, &block|
        
        redirect_to profile_path, notice: 'Endereço removido com Sucesso'
        #render json: response.body

    }
  end

  def updateabout
    RestClient.put('http://pizzaprime.herokuapp.com/webservices/account/updateAbout', { :phone => params[:datas][:phone], :name => params[:datas][:name], :gender => params[:datas][:gender] }, :cookies => { '_session_id' => cookies[:session_id] } ){ |response, request, result, &block|
        
        redirect_to profile_path, notice: 'Perfil Editado com Sucesso'
        #render json: response.body

    }
  end

  def busca_cidades

    consult = RestClient.get 'https://maps.googleapis.com/maps/api/geocode/json?address='+params[:cep][:numero]+'+'+params[:cep][:logradouro].gsub(" ","+")+',+'+params[:cep][:localidade].gsub(" ","+")+',+'+params[:cep][:uf].gsub(" ","+")+'&key=AIzaSyA4VtmtyiHJXI_l5esvm_7Vhdw8epH_3_Q'
    # Google Api Key = AIzaSyA4VtmtyiHJXI_l5esvm_7Vhdw8epH_3_Q
    @address = JSON.parse(consult)

    zip = params[:cep][:cep].gsub("-","").to_i
    zone = Zone.where(:initial_zip.lte => zip, :final_zip.gte => zip)
    if zone.count == 0

      ids = Mongoid.default_client["zones"].find(area:
          { "$geoIntersects" =>
            { "$geometry" =>
                { type: "Point", coordinates: [@address['results'][0]['geometry']['location']['lat'], @address['results'][0]['geometry']['location']['lng']] }
            }
          }
        )

      if ids.count == 0
        @states = Store.distinct(:state)
        @error_cep = true
        render 'index'
      else
        
        @store = Store.mapStores([Store.find(ids.distinct(:store_id).first)]).first
        session[:store] = {}
        session[:store][:id] = @store[:id].to_s
        session[:store][:name] = @store[:name]
        session[:store][:uf] = params[:cep][:uf]
        session[:user] = {}
        session[:user][:bairro] = params[:cep][:bairro]
        session[:user][:cep] = params[:cep][:cep]
        session[:user][:uf] = params[:cep][:uf]
        session[:user][:localidade] = params[:cep][:localidade]
        session[:user][:logradouro] = params[:cep][:logradouro]
        session[:user][:number] = params[:cep][:numero] 

        redirect_to cardapio_path

      end

    else

        @store = Store.mapStores([zone.first.store]).first
        session[:store] = {}
        session[:store][:id] = @store[:id].to_s
        session[:store][:name] = @store[:name]
        session[:store][:uf] = params[:cep][:uf]
        session[:user] = {}
        session[:user][:bairro] = params[:cep][:bairro]
        session[:user][:cep] = params[:cep][:cep]
        session[:user][:uf] = params[:cep][:uf]
        session[:user][:localidade] = params[:cep][:localidade]
        session[:user][:logradouro] = params[:cep][:logradouro]
        session[:user][:number] = params[:cep][:numero] 

        redirect_to cardapio_path

    end
  end
  
  def selend
    @address = Address.find(params[:id])

    RestClient.get('http://pizzaprime.herokuapp.com/webservices/stores/getAvailableStores', { :params => {  zip: @address.zip, address_id: @address.id  },  :cookies => { '_session_id' => cookies[:session_id] }  } ){ |response, request, result, &block|
      if response.code == 340
        redirect_to cardapio_path, alert: 'Ainda não há nenhuma loja que atende a sua região. Cadastre um endereço diferente em Meu Perfil'
      elsif response.code == 401
        redirect_to cardapio_path, alert: 'Faça seu login para continuar comprando'
      elsif response.code == 500
        redirect_to cardapio_path, alert: 'Não foi possivel checar seu endereço, por favor tente novamente mais tarde'
      else
        @addresses = JSON.parse(response.body)
        if @addresses.length == 1
          session[:address_id] = @address.id.to_s
          session[:store] = {}
          session[:store][:id] = @addresses[0]['id'].to_s
          session[:store][:name] = @addresses[0]['name']
          session[:store][:uf] = @address.state
          session[:user] = {}
          session[:user][:bairro] = @address.neighborhood
          session[:user][:cep] = @address.zip
          session[:user][:uf] = @address.state
          session[:user][:localidade] = @address.city
          session[:user][:logradouro] = @address.street
          session[:user][:number] = @address.number 

          #render json: { :address => session[:address_id], :loja => session[:store], :user => session[:user] }
        else
          #render json: 'Escolha uma loja'
        end
        redirect_to cardapio_path
      end  
    }

    
  end

  def applycoupon

    @pedido = {} 
    @pedido[:pizzas] = []
    if !session[:pizzas].nil? 
      session[:pizzas].each do |key, p|
          novo = p
          @pedido[:pizzas].push(novo)
      end # pizzas
    end
    @pedido[:sweet_pizzas] = []
    if session[:sweet_pizzas].nil?
    else
      session[:sweet_pizzas].each do |key, p|
          novo = p
          @pedido[:sweet_pizzas].push(novo)
      end # sweet_pizzas
    end
    @pedido[:beverages] = []
    if session[:bebidas].nil?
    else
      session[:bebidas].each do |key, p|
        novo = { :id => key, :quantity => p['qtd'], :fidelity => false }
        @pedido[:beverages].push(novo)
      end 
    end

    if !session[:combo].nil?
      @pedido[:combos] = session[:combo]
    end

    @pedido[:store_id] = session[:store]['id']

    @pedido[:address_id] = session[:address_id]

    @cupon = {}
    @cupon[:order] = @pedido
    @cupon[:store_id] = session[:store]['id']
    @cupon[:udid] = request.remote_ip
    @cupon[:coupon] = params[:coupon][:name]


    RestClient.post('http://pizzaprime.herokuapp.com/webservices/coupons/checkCoupon',   @cupon  , :cookies => { '_session_id' => cookies[:session_id] } ){ |response, request, result, &block|
        if response.code == 401
          @resposta = 'Usuário não logado, faça seu login para continuar comprando'
        elsif response.code == 340
          @resposta = 'Nenhuma Loja foi encontrada'
        elsif response.code == 341
          @resposta = 'Cupom Expirado!'
        elsif response.code == 342
          @resposta = 'Cupom não encontrado'
        elsif response.code == 343
          @resposta = 'Condições não Satisfeitas'
        elsif response.code == 344
          @resposta = 'Cupom já utilizado'
        elsif response.code == 500
          @resposta = 'Não foi possível realizar seu pedido, verique seus dados de cadastro e tente novamente'
        else
          @teste = JSON.parse(response.body)
          session[:coupon] = @teste

app/helpers/loja_helper.rb
module LojaHelper
end

app/views/loja/cep.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" >
        <meta name="viewport" content="width=device-width, initial-scale=1" > 
        <link href="https://fonts.googleapis.com/css?family=Titillium+Web:200,300,400,700" rel="stylesheet">
        <link rel="stylesheet" href="/css/bootstrap.css" >
        <link rel="stylesheet" href="/css/css.css" >
        <link rel='shortcut icon' type='image/x-icon' href='/images/favicon.ico' />
        <script src="https://use.fontawesome.com/7f3531401e.js"></script>
        
        <title>Pizza Prime</title>
        <!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1581601698520946'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1581601698520946&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->

    </head>
    <body class="fundo_cep">
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60507233-1', 'auto');
  ga('send', 'pageview');

</script>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=662174687264933";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

        <%= render :partial => 'home/header', :locals => {:page => 'loja'} %>
        
        <div class="stores">
        	<div>
        		<div class="content center">
        			<ul class="states">
        				<% @states.each do |state| %>
        					<li>
                                <%
                                
                                case state
                                when 'SP'
                                    concat 'São Paulo'
                                when 'RJ'
                                    concat 'Rio de Janeiro'
                                when 'SC'
                                    concat 'Santa Catarina'
                                when 'RS'
                                    concat 'Rio Grande do Sul'
                                when 'PR'
                                    concat 'Paraná'
                                when 'AP'
                                    concat 'Amapá'
                                else
                                    concat ''
                                end
                                
                                %>
                            </li>
        				<% end %>
        			</ul>
        		</div>
        	</div>
        </div>

        <div style="
                padding:50px 0 100px; 
background: -moz-radial-gradient(center, ellipse cover, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 29%, rgba(255,255,255,0) 70%, rgba(255,255,255,0) 100%);
background: -webkit-radial-gradient(center, ellipse cover, rgba(255,255,255,1) 0%,rgba(255,255,255,1) 29%,rgba(255,255,255,0) 70%,rgba(255,255,255,0) 100%);
background: radial-gradient(ellipse at center, rgba(255,255,255,1) 0%,rgba(255,255,255,1) 29%,rgba(255,255,255,0) 70%,rgba(255,255,255,0) 100%); 
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#00ffffff',GradientType=1 );
                ">
            <div class="center content">

                <h2 class="fundo-faixa">Complete seu endereço:</h2>
                <div style="max-width:700px; margin:0 auto">
                <%= form_for :cep, url: busca_cidades_path do |f| %>
                    <%= f.hidden_field :bairro, :value => I18n.transliterate(@address['bairro']) %>
                    <%= f.hidden_field :cep, :value => @address['cep'] %>
                    <div class="row formcep">
                        <div class="col-md-3">
                            <%= f.text_field :uf, :value => @address['uf'], :readonly => true, :class => 'form-control end' %>
                        </div>
                        <div class="col-md-9">
                            <%= f.text_field :localidade, :value => I18n.transliterate(@address['localidade']), :readonly => true, :class => 'form-control end' %>
                        </div>
                    </div>
                    <div class="row formcep">
                        <div class="col-md-10">
                            <%= f.text_field :logradouro, :value => I18n.transliterate(@address['logradouro']), :readonly => true, :class => 'form-control end' %>
                        </div>
                        <div class="col-md-2">
                            <%= f.text_field :numero, :placeholder => 'Nº', :class => 'form-control end' %>
                        </div>
                    </div>
                    <button class="btn-cep" type="button" onclick="history.go(-1)">Voltar</button>
                    <%= f.submit 'OK', :class => 'btn-cep' %>

                <% end %>
                </div>
                <br>
            
            </div>
        </div>
       <div id="footer">
            <div>
            <div class="content row">
                <div class="col-md-2">
                    <img src="/images/logo-slide.png" alt="Pizza Prime" title="Pizza Prime" style="width:100%;">
                </div>
                <div class="col-md-3 center links" >
                    <p class="footer-title">Mapa do Site</p>
                    
                    <a href="">Home</a><br>
                    <% if session[:store].blank? %>  
                        <a href="<%= loja_path %>">Unidades/Cardápios</a><br>
                    <% else %>
                        <a href="<%= cardapio_path %>">Unidades/Cardápios</a><br>
                    <% end %>
                    <a href="">A Pizza Prime</a><br>
                    <a href="">Trabalhe Conosco/Contato</a><br>
                    <a href="">Blog</a><br>
                </div>
                <div class="col-md-7 center" >
                    <p class="footer-title">Acompanhe a nossa fan page :)</p>                  

                    <div class="fb-page" data-href="https://www.facebook.com/Pizza.Prime.Brasil/" data-tabs="timeline" data-width="400" data-height="200" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/Pizza.Prime.Brasil/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Pizza.Prime.Brasil/">Pizza Prime</a></blockquote></div>

                </div>
            </div>
            <div class="content row" style="color:#fff; margin:40px auto 0; border-top:1px solid #6a1112; padding:10px 0 5px">
                <div class="col-md-6 text-right">
                    Pizza Prime &copy; 2017 - Todos os direitos reservados
                </div>
                <div class="col-md-6">
                    CNPJ nº 12.034.651/0001-81
                </div>
            </div>
            </div>
        </div>

        <script type="text/javascript" src="/js/jquery-3.1.1.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.js"></script>
        <script type="text/javascript" src="/js/main.js"></script>
        <script type="text/javascript" src="/js/mask.js"></script>
        <script type="text/javascript">
            $(function(){

                $('.cep').mask('99999-999');

            });
        </script>
        <script type="text/javascript" async src="https://d335luupugsy2.cloudfront.net/js/loader-scripts/06c0c772-6f76-429f-8082-c86ab41812f5-loader.js" ></script>
    </body>
</html>

app/views/loja/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" >
        <meta name="viewport" content="width=device-width, initial-scale=1" > 
        <link href="https://fonts.googleapis.com/css?family=Titillium+Web:200,300,400,700" rel="stylesheet">
        <link rel="stylesheet" href="/css/bootstrap.css" >
        <link rel="stylesheet" href="/css/css.css" >
        <link rel='shortcut icon' type='image/x-icon' href='/images/favicon.ico' />
        <script src="https://use.fontawesome.com/7f3531401e.js"></script>

        <title>Pizza Prime</title>
        <!-- Facebook Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1581601698520946'); // Insert your pixel ID here.
        fbq('track', 'PageView');
        </script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=1581601698520946&ev=PageView&noscript=1"
        /></noscript>
        <!-- DO NOT MODIFY -->
        <!-- End Facebook Pixel Code -->
        
    </head>
    <body class="fundo_cep">
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60507233-1', 'auto');
  ga('send', 'pageview');

</script>
        <%= render :partial => 'home/header', :locals => {:page => 'loja'} %>
        
        <div class="stores">
        	<div>
        		<div class="content center">
        			<ul class="states">
        				<% @states.each do |state| %>
        					<li>
                                <%
                                
                                case state
                                when 'SP'
                                    concat 'São Paulo'
                                when 'RJ'
                                    concat 'Rio de Janeiro'
                                when 'SC'
                                    concat 'Santa Catarina'
                                when 'RS'
                                    concat 'Rio Grande do Sul'
                                when 'PR'
                                    concat 'Paraná'
                                when 'AP'
                                    concat 'Amapá'
                                else
                                    concat ''
                                end
                                
                                %>
                            </li>
        				<% end %>
        			</ul>
        		</div>
        	</div>
        </div>
        
        <div style="
                padding:50px 0 100px;
background: -moz-radial-gradient(center, ellipse cover, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 29%, rgba(255,255,255,0) 70%, rgba(255,255,255,0) 100%);
background: -webkit-radial-gradient(center, ellipse cover, rgba(255,255,255,1) 0%,rgba(255,255,255,1) 29%,rgba(255,255,255,0) 70%,rgba(255,255,255,0) 100%);
background: radial-gradient(ellipse at center, rgba(255,255,255,1) 0%,rgba(255,255,255,1) 29%,rgba(255,255,255,0) 70%,rgba(255,255,255,0) 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#00ffffff',GradientType=1 );
                ">
            <div class="center content">
                <% if @error_cep %>
                    <h2 class="fundo-faixa">OPS!</h2>
                    <p style=" font-size:20px; max-width:700px; margin:-30px auto 0; ">Sua região ainda não está disponível!<br>Insira seu email para receber uma mensagem quando a rede PIZZA PRIME estiver disponível na sua região.</p>
                    <br>
                    <div style="max-width:700px; margin:0 auto">
                        <%= form_for :email, url: rss_path do |f| %>
                            <%= f.text_field :cep, :placeholder => 'Digite seu email', :class => 'form-control end formcep' %><br>
                            <%= f.submit 'OK', :class => 'btn-cep' %>
                        <% end %>
                    </div>
                <% else %>
                    <h2 class="fundo-faixa">Digite o seu cep abaixo:</h2>
                    <br>
                    <div style="max-width:700px; margin:0 auto">
                        <%= form_for :cep, url: cep_path do |f| %>
                            <%= f.text_field :cep, :placeholder => 'Digite seu cep', :class => 'form-control cep' %><br>
                            <%= f.submit 'OK', :class => 'btn-cep' %>
                        <% end %>
                    </div>
                    <br>
                <% end %>
            </div>
        </div>
    
        <% if flash[:alert] %>       
            <div id="flash" class="modal fade" tabindex="-1" role="dialog">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Mensagem do Sistema</h4>
                  </div>
                  <div class="modal-body">
                    <p><%= flash[:alert] %></p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
        <% end %>

        <script type="text/javascript" src="/js/jquery-3.1.1.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.js"></script>
        <script type="text/javascript" src="/js/main.js"></script>
        <script type="text/javascript" src="/js/mask.js"></script>
        <script type="text/javascript">
            $(function(){

                $('.cep').mask('99999-999');

                <% if flash[:alert] %>
                    $('#flash').modal('show');
                <% end %>

            });
        </script>
        <script type="text/javascript" async src="https://d335luupugsy2.cloudfront.net/js/loader-scripts/06c0c772-6f76-429f-8082-c86ab41812f5-loader.js" ></script>
    </body>
</html>