config/routes.rb
Rails.application.routes.draw do
    
  get 'users/index'

  get 'users/new'

  get 'users/show'

  get 'users/edit'

  get 'users/create'

  get 'users/update'

  get 'users/destroy'

  	get 'loja' => 'loja#index', as: :loja
  	post 'busca_cidades' => 'loja#busca_cidades', as: :busca_cidades
  	get 'cardapio' => 'loja#cardapio', as: :cardapio
    get 'cardapio/:state' => 'loja#cardapio_state', as: :cardapio_state
    get 'cardapio/:state/:name' => 'loja#cardapio_state_name', as: :cardapio_state_name
  	post 'login' => 'loja#login', as: :login
  	get 'pizzas/:guide' => 'loja#pizzas', as: :pizzas
  	get 'modeljson' => 'loja#modeljson', as: :modeljson
  	get 'cart' => 'loja#cart', as: :cart
    get 'checkout' => 'loja#checkout', as: :checkout
    post 'checkout_confirm' => 'loja#checkout_confirm', as: :checkout_confirm
    post 'add_combo' => 'loja#add_combo', as: :add_combo
    post 'add_combo_sweet' => 'loja#add_combo_sweet', as: :add_combo_sweet
    post 'add_combo_beverages' => 'loja#add_combo_beverages', as: :add_combo_beverages
  	post 'add_cart' => 'loja#add_cart', as: :add_cart
    post 'add_sweet' => 'loja#add_sweet', as: :add_sweet
    post 'edit_cart' => 'loja#edit_cart', as: :edit_cart
    post 'edit_sweet' => 'loja#edit_sweet', as: :edit_sweet
    get 'del/:name' => 'loja#del', as: :del
    get 'sweet_del/:name' => 'loja#sweet_del', as: :sweet_del
    post 'cep' => 'loja#cep', as: :cep
    post 'rss' => 'loja#rss', as: :rss
    get 'tamanho/:id' => 'loja#tamanho', as: :tamanho
    get 'massa/:id' => 'loja#massa', as: :massa
    get 'borda/:id' => 'loja#borda', as: :borda
    get 'integral' => 'loja#integral', as: :integral
    get 'bebidas/:price/:id/:qtd' => 'loja#bebidas', as: :bebidas
    get 'bebemenos/:id' => 'loja#bebemenos', as: :bebemenos
    get 'profile' => 'loja#profile', as: :profile
    get 'combo/:id' => 'loja#combo', as: :combo
    get 'limparcart' => 'loja#limparcart', as: :limparcart
    get 'remove_combo/:id' => 'loja#remove_combo', as: :remove_combo
    get 'remove_pizza_combo/:id' => 'loja#remove_pizza_combo', as: :remove_pizza_combo
    get 'remove_doce_combo/:id' => 'loja#remove_doce_combo', as: :remove_doce_combo
    get 'remove_bebida_combo/:id' => 'loja#remove_bebida_combo', as: :remove_bebida_combo

    get 'unidades' => 'home#unidades', as: :unidades
    get 'novo_hamburgo' => 'home#novo_hamburgo', as: :novo_hamburgo

    post 'contato' => 'home#contato', as: :contato
    post 'applycoupon' => 'loja#applycoupon', as: :applycoupon

    get 'removeaddress/:id' => 'loja#removeaddress', as: :removeaddress
    get 'removecard/:id' => 'loja#removecard', as: :removecard

    get 'selend/:id' => 'loja#selend', as: :selend

    post 'updateabout' => 'loja#updateabout', as: :updateabout
    post 'addaddress' => 'loja#addaddress', as: :addaddress
    post 'addcard' => 'loja#addcard', as: :addcard
    get 'cadastre' => 'home#cadastre', as: :cadastre

    post 'novouser' => 'home#novouser', as: :novouser

    get 'home' => 'home#index', as: :home
    get 'logout' => 'loja#logout', as: :logout

    get 'auth/facebook' => 'loja#loginfacebook', as: :auth_provider
    get 'auth/facebook/callback' => 'loja#loginfacebook'
    get 'auth/failure' => 'loja#login#failure', as: "auth_failure"

    root 'home#index'
     
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    if session[:store].blank? && session[:user].blank?
      @combos = Combo.all.order(created_at: :asc)
    else
      RestClient.get('http://pizzaprime.herokuapp.com/webservices/stores/getCombos', { :params => { store_id: session[:store]['id']  },  :cookies => { '_session_id' => cookies[:session_id] }  } ){ |response, request, result, &block|
        if response.code == 340
          redirect_to cardapio_path, alert: 'Ainda não há nenhuma loja que atende a sua região. Cadastre um endereço diferente em Meu Perfil'
        elsif response.code == 401
          cookies[:session_id] = nil
          
          session[:address_id] = nil
          session[:store] = nil
          session[:user] = nil
          session[:logged] = nil
          session[:name] = nil
          session[:email] = nil
          session[:picture] = nil
          session[:gender] = nil
          session[:facebook] = nil
          session[:balance] = nil
          session[:phone] = nil
          session[:cpf] = nil
          session[:caixa] = nil
          session[:pizzas] = nil
          session[:bebidas] = nil
          session[:tamanho] = nil
          session[:massa] = nil
          session[:borda] = nil
          session[:integral] = nil
          session[:combo] = nil
          session[:coupon] = nil
          redirect_to home_path, alert: 'Faça seu login para continuar comprando'
          
        elsif response.code == 500
          redirect_to cardapio_path, alert: 'Não foi possivel checar seu endereço, por favor tente novamente mais tarde'
        elsif response.code == 302
          cookies[:session_id] = nil
          
          session[:address_id] = nil
          session[:store] = nil
          session[:user] = nil
          session[:logged] = nil
          session[:name] = nil
          session[:email] = nil
          session[:picture] = nil
          session[:gender] = nil
          session[:facebook] = nil
          session[:balance] = nil
          session[:phone] = nil
          session[:cpf] = nil
          session[:caixa] = nil
          session[:pizzas] = nil
          session[:bebidas] = nil
          session[:tamanho] = nil
          session[:massa] = nil
          session[:borda] = nil
          session[:integral] = nil
          session[:combo] = nil
          session[:coupon] = nil
          redirect_to home_path, alert: 'Faça seu login para continuar comprando'
        else
          @combos = JSON.parse(response.body)
        end  
      }
    end
      @stores = Store.all
  end

  def unidades
  end

  def novo_hamburgo
  end

  def cadastre
    @states = Store.distinct(:state)
  end
    
  def contato
    if ContactMailer.contact_email(params[:contact]).deliver
      redirect_to root_path, notice: 'Mensagem enviada com sucesso'
    else
      redirect_to root_path, alert: 'Erro no envio da mensagem'
    end
  end

  def novouser
    RestClient.post('http://pizzaprime.herokuapp.com/webservices/login/signup',  { name: params[:user][:name],  email: params[:user][:email], cpf: params[:user][:cpf], password: params[:user][:password]  }){|response, request|

    if response.code == 200

      redirect_to cardapio_path, :notice => 'Usuário criado com sucesso'
    else
      if response.code == 403
        redirect_to cardapio_path, :alert => 'Usuário já cadastrado, Faça o login para continuar comprando!'
      elsif response.code == 500
        redirect_to cadastre_path, :alert => 'Não foi possível cadastrar usuário, por favor tente novamente mais tarde!'
      end
      
    end
    
    }
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<div id="footer">
            <div>
            <div class="content">
            <div class="content row">
                <div class="col-md-2">
                    <img src="/images/logo-slide.png" alt="Pizza Prime" title="Pizza Prime" style="width:100%;">
                </div>
                <div class="col-md-3 center links" >
                    <p class="footer-title">MAPA DO SITE</p>
                    
                    <a href="">Home</a><br>
                    <% if session[:store].blank? %>  
                        <a href="<%= loja_path %>">Unidades/Cardápios</a><br>
                    <% else %>
                        <a href="<%= cardapio_path %>">Unidades/Cardápios</a><br>
                    <% end %>
                    <a href="">A Pizza Prime</a><br>
                    <a href="">Trabalhe Conosco/Contato</a><br>
                    <a href="">Blog</a><br>
                </div>
                <div class="col-md-7 center" >
                    <p class="footer-title">ACOMPANHE NOSSA FAN PAGE :)</p>                  

                    <div class="fb-page" data-href="https://www.facebook.com/Pizza.Prime.Brasil/" data-tabs="timeline" data-width="400" data-height="200" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/Pizza.Prime.Brasil/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Pizza.Prime.Brasil/">Pizza Prime</a></blockquote></div>
                    
                </div>
            </div>
            <div class="content row" style="color:#fff; margin:40px auto 0; border-top:1px solid #6a1112; padding:10px 0 5px">
                <div class="col-md-6 text-right">
                    Pizza Prime &copy; 2017 - Todos os direitos reservados
                </div>
                <div class="col-md-6">
                    CNPJ nº 12.034.651/0001-81
                </div>
            </div>
            </div>
            </div>
        </div>

app/views/home/_header.html.erb
        <div class="header">
            <div class="content row">
                <div class="col-md-2">
                    <img src="/images/logo-slide.png" onclick="javascript: location.href='<%= root_path %>'" alt="Pizza Prime" title="Pizza Prime" class="logo pointer" />
                    <div class="dropdown right">
                      <button id="dLabel" class="hamburguer" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bars"></i>
                      </button>
                      <ul class="dropdown-menu" style="width:100%; position:absolute;" aria-labelledby="dLabel">
                        <li <% if page == 'home' %> class="active" <% end %> ><a href="<%= root_path %>">Home</a></li>
                        <li <% if page == 'unidades' %> class="active" <% end %> ><a href="<%= unidades_path %>">Unidades</a></li>
                        <li><a href="#apizza" onclick="row(this)">A Pizza Prime</a></li>
                        <li><a href="#trabalhe" onclick="row(this)" >Contato</a></li>
                        <li><a href="http://blog.pizzaprime.com.br/" target="_blank">Blog</a></li>
                        <li>
                            <% if session[:store].blank? %>  
                                <a href="<%= loja_path %>"><strong>Peça Agora</strong></a>
                            <% else %>
                                <a href="<%= cardapio_path %>"><strong>Peça Agora</strong></a>
                            <% end %>
                        </li>
                      </ul>
                    </div>
                </div>
                <div class="col-md-10 text-right">
                    
                    <ul class="menu">
                        <li <% if page == 'home' %> class="active" <% end %> ><a href="<%= root_path %>">Home</a></li>
                        <li <% if page == 'unidades' %> class="active" <% end %> ><a href="<%= unidades_path %>">Unidades</a></li>
                        <li><a href="#apizza" onclick="row(this)">A Pizza Prime</a></li>
                        <li><a href="#trabalhe" onclick="row(this)" >Contato</a></li>
                        <li><a href="http://blog.pizzaprime.com.br/" target="_blank">Blog</a></li>
                        <li>
                            <% if session[:store].blank? %>  
                                <a href="<%= loja_path %>"><strong>Peça Agora</strong></a>
                            <% else %>
                                <a href="<%= cardapio_path %>"><strong>Peça Agora</strong></a>
                            <% end %>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </div>

app/views/home/cadastre.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" >
        <meta name="viewport" content="width=device-width, initial-scale=1" > 
        <link href="https://fonts.googleapis.com/css?family=Titillium+Web:200,300,400,700" rel="stylesheet">
        <link rel="stylesheet" href="/css/bootstrap.css" >
        <link rel="stylesheet" href="/css/css.css" >
        <link rel='shortcut icon' type='image/x-icon' href='/images/favicon.ico' />
        <script src="https://use.fontawesome.com/7f3531401e.js"></script>
        
        <title>Pizza Prime</title>
        <!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1581601698520946'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1581601698520946&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->

    </head>
    <body>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60507233-1', 'auto');
  ga('send', 'pageview');

</script>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=662174687264933";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

        <%= render :partial => 'header', :locals => {:page => 'loja'} %>
        
        <div class="stores">
        	<div>
        		<div class="content center">
        			<ul class="states">
        				<% @states.each do |state| %>
        					<li>
                                <%
                                
                                case state
                                when 'SP'
                                    concat 'São Paulo'
                                when 'RJ'
                                    concat 'Rio de Janeiro'
                                when 'SC'
                                    concat 'Santa Catarina'
                                when 'RS'
                                    concat 'Rio Grande do Sul'
                                when 'PR'
                                    concat 'Paraná'
                                when 'AP'
                                    concat 'Amapá'
                                else
                                    concat ''
                                end
                                
                                %>
                            </li>
        				<% end %>
        			</ul>
        		</div>
        	</div>
        </div>
        
        <div class="row content text-center">
            <div class="col-md-12">
                <h2 class="fundo-faixa">Cadastre-se</h2>
                <%= form_for :user, url: novouser_path do |f| %>
                    <div class="row formcep">
                        <div class="col-md-6">
                            <%= f.text_field :name, :placeholder => 'Nome', :class => 'form-control end' %>
                        </div>
                        <div class="col-md-6">
                            <%= f.text_field :cpf,  :placeholder => 'CPF', :class => 'form-control end' %>
                        </div>
                    </div>
                    <div class="row formcep">
                        <div class="col-md-6">
                            <%= f.text_field :email, :placeholder => 'Email', :class => 'form-control end' %>
                        </div>
                        <div class="col-md-6">
                            <%= f.text_field :password, :placeholder => 'Senha', :class => 'form-control end' %>
                        </div>
                    </div>
                    <%= f.submit 'Cadastrar', :class => 'btn-cep' %>

                <% end %>
            </div>
        </div><br>
        <br>
        <%= render 'footer' %>

        <script type="text/javascript" src="/js/jquery-3.1.1.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.js"></script>
        <script type="text/javascript" src="/js/main.js"></script>
        <script type="text/javascript" src="/js/mask.js"></script>
        <script type="text/javascript">
            $(function(){

                $('#user_cpf').mask('999.999.999-99');

            });
        </script>

        <script type="text/javascript" async src="https://d335luupugsy2.cloudfront.net/js/loader-scripts/06c0c772-6f76-429f-8082-c86ab41812f5-loader.js" ></script>
    </body>
</html>